### ISSUE TITLE
--tap

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-tex#1]
Have you tried passing --tap to brew test-bot? Looks like it should work like `--tap=domt4/tex`.

**Comment by DomT4** [comment]
As in ` brew test-bot $TRAVIS_COMMIT --no-bottle --skip-setup -d --tap=domt4/tex `?

I've just given you and the other maintainers push access here, if you want to try things out.

**Comment by DomT4** [comment]
Closed per successful migration to Homebrew :+1:
